version: "3"
services:
  node:
    build: ./image
    working_dir: /home/node/app
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    command: "npm run all"
