version: "3"
services:
  node:
    image: node:csc
    build:
      context: ./services/node
    environment:
      - NODE_ENV=production
      - PORT=80
    env_file: secrets/node.env
    ports:
      - "80:80"
    networks:
      - redis
      - postgres
      - mongo
    depends_on:
      - redis
      - postgres
      - mongo

  redis:
    image: redis:csc
    build:
      context: ./services/redis
    volumes:
      - redis_dbdata:/data
    networks:
      - redis

  postgres:
    image: postgres:csc
    build:
      context: ./services/postgres
    volumes:
      - postgres_dbdata:/var/lib/postgresql/data
    env_file: secrets/postgres.env
    networks:
      - postgres

  mongo:
    image: mongo:csc
    build:
      context: ./services/mongo
    volumes:
      - mongo_dbdata:/data/db
    env_file: secrets/mongo.env
    networks:
      - mongo

networks:
  redis:
  postgres:
  mongo:

volumes:
  postgres_dbdata:
  redis_dbdata:
  mongo_dbdata:
