version: "3"
services:
  node:
    build: ./image
    working_dir: /home/node/app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=80
    volumes:
      - ./:/home/node/app
    expose:
      - "80"
    ports:
      - "80:80"
    command: "npm run all"
