version: "3"
services:
  node:
    image: node:csc
    build:
      context: ./services/node
    environment:
      - NODE_ENV=production
      - PORT=80
    env_file: secrets/node.env
    depends_on:
      - redis
      - postgres
      - mongo
    ports:
      - "80:80"
    networks:
      - redis
      - postgres
      - mongo
    command: "npm start"

  redis:
    image: redis:csc
    build:
      context: ./services/redis
    volumes:
      - redis_dbdata:/data
    networks:
      - redis
    expose:
      - "6379"
    command: "/usr/local/bin/redis-server /etc/redis.conf"

  postgres:
    image: postgres:csc
    build:
      context: ./services/postgres
    volumes:
      - postgres_dbdata:/var/lib/postgresql/data
    env_file: secrets/postgres.env
    networks:
      - postgres
    expose:
      - "5432"

  mongo:
    image: mongo:csc
    build:
      context: ./services/mongo
    volumes:
      - mongo_dbdata:/data/db
    env_file: secrets/mongo.env
    networks:
      - mongo
    expose:
      - "27017"

networks:
  redis:
  postgres:
  mongo:

volumes:
  postgres_dbdata:
  redis_dbdata:
  mongo_dbdata:
